# Generated by Django 4.0.2 on 2022-03-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/images/np.jpeg', null=True, upload_to='images'),
        ),
    ]
